image: python:3.9-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PACKAGE_NAME: eyeo

cache:
  policy: pull
  paths:
    - .cache/pip/
    - venv/

before_script:
  - /usr/bin/python3 -V  # Print out python version for debugging
  - env| egrep 'CI_|PIP_' || true

stages:
  - prep
  - build
  - install
  - test
  - docs

prep:
  stage: prep
  cache:
    policy: push
  script:
    - which python3
    - command -v python3
    - env | egrep PY || true
    - unset PYTHONPATH
    - /usr/bin/python3 -m venv venv
    - . venv/bin/activate
    - pip install --upgrade pip build wheel setuptools

build:
  stage: build
  script:
    - . venv/bin/activate
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl
  tags:
    - container

test-install:
  stage: install
  script:
    - . venv/bin/activate
    - pip list
    - pip install dist/*.whl
    - pip list
  tags:
    - container

run-examples:
  stage: test
  script:
    - . venv/bin/activate
    - pip list
    - pip install dist/*.whl
    - pip list
    - python3 -m eyeo.examples
    - python3 -m eyeo.stringify_examples
  tags:
    - container

.docs-stage:
  stage: docs
  script:
    - . venv/bin/activate
    - pip list
    - pip install pytest pdoc3
    - pip install dist/*.whl
    - pip list
    - mkdir -p public
    - PYTHONPATH=src pdoc $PACKAGE_NAME > public/README_api.md
    - PYTHONPATH=src pdoc --html -o public/html $PACKAGE_NAME
  artifacts:
    paths:
      - public
  tags:
    - container

docs:
  extends: .docs-stage
  except:
    - master
    
pages:
  extends: .docs-stage
  only:
    - master
