image: python:3.9-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PACKAGE_NAME: eyeo

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - env| egrep 'CI_|PIP_'

stages:
  - build
  - install
  - test
  - docs

build:
  stage: build
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install build
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl
  tags:
    - container

test-install:
  stage: install
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install dist/*.whl
    - pip list
  tags:
    - container

run-examples:
  stage: test
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip list
    - pip install dist/*.whl
    - pip list
    - python3 -m eyeo.examples
    - python3 -m eyeo.stringify_examples
  tags:
    - container

docs:
  stage: docs
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip list
    - ls -al venv/lib/python3*/site-packages/pdoc3-*-py*.egg-info/requires.txt || true
    - pip install --upgrade pip
    - pip install --upgrade wheel setuptools
    - pip install pdoc3 || true
    - ls -alR venv/lib/python*/*-packages/pdoc3-*-py*egg* || true
    - chmod -R u+rwX venv/
    - pip install pytest
    - mkdir -p docs
    - pip install dist/*.whl
    - pip list
    - PYTHONPATH=src pdoc $PACKAGE_NAME > README_api.md
    - PYTHONPATH=src pdoc --html -o docs/html $PACKAGE_NAME
  artifacts:
    paths:
      - README_api.md
      - docs/html/$(PACKAGE_NAME)/**/*.*
  tags:
    - container
