include: .gitlab-ci.pymodule.yml

variables:
  PACKAGE_NAME: eyeo

prep:
  extends: .prep

build:
  extends: .build

test-install:
  extends: .test-install

run-examples:
  extends: .run-examples
  script:
    - if [[ -d /venv ]]; then . /venv/bin/activate; else python3 -m venv venv; . venv/bin/activate ; fi
    - pip install $PIP_OPTIONS dist/*.whl
    - python3 -m eyeo.examples
    - python3 -m eyeo.stringify_examples

docs:
  extends: .docs

pages:
  extends: .pages

upload-successful:
  extends: .upload-successful
